### ISSUE TITLE
src和lib文件夹下文件一样，除了版本号

### ISSUE THREAD

**Issue by gooking** [thundernet8/AlipayOrdersSupervisor#13]
src和lib文件夹下文件一样，除了版本号

SRC 下是 1.6
lib下是1.5

另外，能否介绍下这两个文件夹有什么区别呀？

**Comment by thundernet8** [comment]
src内是源码，lib是编译出来的，编译的没更新，现在已更新

**Comment by gooking** [comment]
那顺便问下，我要自己从 src 编译到  lib 应该执行什么命令呢？

**Comment by thundernet8** [comment]
npm run build


发送自我的三星盖乐世智能手机。
-------- 原始信息 --------由： gooking <notifications@github.com> 日期: 2018/2/5  07:02  (GMT+08:00) 收件人： thundernet8/AlipayOrdersSupervisor <AlipayOrdersSupervisor@noreply.github.com> 抄送： Touchumind <chinash2010@gmail.com>, State change <state_change@noreply.github.com> 主题： Re: [thundernet8/AlipayOrdersSupervisor] src和lib文件夹下文件一样，除了版本号 (#13) 
那顺便问下，我要自己从 src 编译到  lib 应该执行什么命令呢？

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thundernet8/AlipayOrdersSupervisor","title":"thundernet8/AlipayOrdersSupervisor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thundernet8/AlipayOrdersSupervisor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gooking in #13: 那顺便问下，我要自己从 src 编译到  lib 应该执行什么命令呢？"}],"action":{"name":"View Issue","url":"https://github.com/thundernet8/AlipayOrdersSupervisor/issues/13#issuecomment-362947968"}}}
